# Generated by Django 6.0.5 on 2026-06-24 05:30

import apps.files.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0004_crosstenantaccessattempt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoredFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("avatar", "Avatar"),
                            ("community_photo", "Community photo"),
                            ("kyc_doc", "KYC document"),
                            ("payment_evidence", "Payment evidence"),
                            ("chat_attachment", "Chat attachment"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "original_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("size_bytes", models.BigIntegerField(default=0)),
                (
                    "checksum_sha256",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "created_key",
                    models.CharField(default="", editable=False, max_length=64),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255, upload_to=apps.files.models._upload_to
                    ),
                ),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending scan"),
                            ("clean", "Clean"),
                            ("infected", "Infected"),
                            ("skipped", "Skipped (no scanner)"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["owner", "kind"], name="file_owner_kind_idx"),
                    models.Index(fields=["deleted_at"], name="file_deleted_idx"),
                ],
            },
        ),
    ]
