# Generated by Django 5.2.14 on 2026-05-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='next_fire_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='scheduled_for',
            field=models.DateTimeField(help_text='When to fire this reminder (or first fire if recurring)'),
        ),
    ]
