# Generated by Django 6.0.5 on 2026-05-16 13:21

import apps.communities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_welfare_shares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='invite_code',
            field=models.CharField(default=apps.communities.models._generate_invite_code, max_length=20, unique=True),
        ),
    ]
