# Generated by Django 5.2.14 on 2026-05-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='communityjoinrequest',
            name='join_req_community_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='communitymembership',
            name='membership_community_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='communitymembership',
            name='membership_user_active_idx',
        ),
        migrations.AlterField(
            model_name='communitymembership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('treasurer', 'Treasurer'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
