# Generated by Django 5.2.14 on 2026-05-22 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_treasurer_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='communityjoinrequest',
            index=models.Index(fields=['community', 'status'], name='joinreq_community_status_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['community', 'is_active'], name='mem_community_active_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['user', 'is_active'], name='mem_user_active_idx'),
        ),
    ]
