# Generated by Django 5.2.14 on 2026-06-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0010_protect_creator_and_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='contribution_permission',
            field=models.CharField(choices=[('admins', 'Admins & Treasurers only'), ('members', 'Any member')], default='admins', max_length=10),
        ),
        migrations.AddField(
            model_name='community',
            name='invite_permission',
            field=models.CharField(choices=[('admins', 'Admins & Treasurers only'), ('members', 'Any member'), ('creator', 'Creator only')], default='admins', max_length=10),
        ),
        migrations.AddField(
            model_name='community',
            name='join_policy',
            field=models.CharField(choices=[('open', 'Open — anyone can join directly'), ('request', 'Request-to-join — admin approval required'), ('invite_only', 'Invite only — via invite link')], default='invite_only', max_length=15),
        ),
        migrations.AddField(
            model_name='community',
            name='max_members',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of active members. Null = unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='member_list_visibility',
            field=models.CharField(choices=[('all', 'All members'), ('admins', 'Admins only')], default='all', max_length=10),
        ),
    ]
