# Generated by Django 5.2.14 on 2026-06-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0011_community_contribution_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='cooling_off_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Days a new member must wait before accessing financial features. 0 = none.'),
        ),
    ]
