# Generated by Django 6.0.5 on 2026-06-22 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0012_community_cooling_off_days"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="communities",
                to="tenants.tenant",
            ),
        ),
    ]
