# Generated by Django 6.0.5 on 2026-07-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0014_alter_community_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitymembership",
            name="notifications_muted",
            field=models.BooleanField(default=False),
        ),
    ]
