# Generated by Django 6.0.5 on 2026-07-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0015_communitymembership_notifications_muted"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("suspended", "Suspended (ops freeze)"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="active",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="communitymembership",
            name="rejoined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
