# Generated by Django 6.0.5 on 2026-07-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0016_community_status_communitymembership_rejoined_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitymembership",
            name="member_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("left", "Left voluntarily"),
                    ("removed", "Removed by owner"),
                    ("banned", "Banned — cannot rejoin"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
