# Generated by Django 6.0.5 on 2026-07-07 06:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0018_backfill_member_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="communityjoinrequest",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="communityjoinrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled by requester"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="communityjoinrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PENDING")),
                fields=("community", "requester"),
                name="joinreq_one_pending_per_pair",
            ),
        ),
    ]
