# Generated by Django 6.0.5 on 2026-07-13 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0019_alter_communityjoinrequest_unique_together_and_more"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="organization",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="community_profile",
                to="organizations.organization",
            ),
        ),
    ]
