# Generated by Django 6.0.5 on 2026-07-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0021_backfill_organizations"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitymembership",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="communitymembership",
            name="pinned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
