# Generated by Django 6.0.5 on 2026-05-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('community_join', 'Community Join'), ('conversation_created', 'Conversation Created'), ('new_message', 'New Message'), ('contribution_payment', 'Contribution Payment'), ('payment_recorded', 'Payment Recorded'), ('contribution_milestone', 'Contribution Milestone'), ('contribution_joined', 'Contribution Joined')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('community_id', models.IntegerField(blank=True, null=True)),
                ('conversation_id', models.IntegerField(blank=True, null=True)),
                ('contribution_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
