# Generated by Django 6.0.5 on 2026-06-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0013_replace_source_event_id_with_event_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationDeadLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "notification_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("channel", models.CharField(db_index=True, max_length=20)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["channel", "-created_at"], name="notif_dlq_channel_idx"
                    )
                ],
            },
        ),
    ]
