# Generated by Django 6.0.5 on 2026-07-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0014_notificationdeadletter"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreferences",
            name="security",
            field=models.BooleanField(default=True),
        ),
    ]
