# Generated by Django 6.0.5 on 2026-07-04 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0015_notificationpreferences_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreferences",
            name="quiet_end",
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
        migrations.AddField(
            model_name="notificationpreferences",
            name="quiet_hours_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationpreferences",
            name="quiet_start",
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
    ]
