# Generated by Django 5.2.14 on 2026-05-31 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_managers_alter_kycprofile_surname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_visibility', models.CharField(choices=[('everyone', 'Everyone'), ('members', 'My communities only'), ('nobody', 'Only me')], default='members', max_length=10)),
                ('photo_visibility', models.CharField(choices=[('everyone', 'Everyone'), ('members', 'My communities only'), ('nobody', 'Only me')], default='everyone', max_length=10)),
                ('contribution_visibility', models.CharField(choices=[('everyone', 'Everyone'), ('members', 'My communities only'), ('nobody', 'Only me')], default='members', max_length=10)),
                ('discoverable', models.BooleanField(default=True)),
                ('show_online_status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
