# Generated by Django 5.2.14 on 2026-05-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_privacypreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycprofile',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='email_verification_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
