# Generated by Django 5.2.14 on 2026-05-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_kycprofile_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycprofile',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/selfies/'),
        ),
    ]
