# Generated by Django 5.2.14 on 2026-05-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_kycprofile_selfie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycprofile',
            name='sub_county',
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='physical_address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
