# Generated by Django 6.0.5 on 2026-07-04 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_usersession"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("transaction_docs", "Transaction supporting documents"),
                            ("address_proof", "Proof of address"),
                            ("kyc_supplement", "Additional KYC information"),
                            ("clarification", "Clarification"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=24,
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                (
                    "detail",
                    models.TextField(
                        help_text="What the user is being asked to provide."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Awaiting your response"),
                            ("submitted", "Submitted — under review"),
                            ("resolved", "Resolved"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("response_note", models.TextField(blank=True, default="")),
                (
                    "document",
                    models.FileField(
                        blank=True, null=True, upload_to="verification/requests/"
                    ),
                ),
                ("review_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="verifreq_user_status_idx"
                    )
                ],
            },
        ),
    ]
