# Generated by Django 6.0.5 on 2026-07-04 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_verificationrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("mpesa", "M-Pesa"),
                            ("card", "Debit or credit card"),
                            ("bank", "Bank account"),
                        ],
                        max_length=8,
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=60)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("unavailable", "Coming soon")],
                        default="active",
                        max_length=12,
                    ),
                ),
                (
                    "mpesa_phone",
                    models.CharField(blank=True, default="", max_length=15),
                ),
                ("card_brand", models.CharField(blank=True, default="", max_length=20)),
                ("card_last4", models.CharField(blank=True, default="", max_length=4)),
                ("card_exp", models.CharField(blank=True, default="", max_length=5)),
                ("bank_name", models.CharField(blank=True, default="", max_length=60)),
                (
                    "bank_account_last4",
                    models.CharField(blank=True, default="", max_length=4),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_default"], name="paymethod_user_default_idx"
                    )
                ],
            },
        ),
    ]
