# Generated by Django 6.0.5 on 2026-07-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_paymentmethod"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycprofile",
            name="verification_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="kycprofile",
            name="verification_detail",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="kycprofile",
            name="verification_provider",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="kycprofile",
            name="verification_ref",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="kycprofile",
            name="verification_state",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
