# Generated by Django 6.0.5 on 2026-07-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_kycprofile_verification_checked_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycprofile",
            name="kra_pin",
            field=models.CharField(blank=True, default="", max_length=11),
        ),
    ]
