# Generated by Django 6.0.5 on 2026-07-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_kycprofile_kra_pin"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycprofile",
            name="resubmission_requested",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
