# Generated by Django 6.0.5 on 2026-07-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_verificationrequest_case"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="member_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=16, null=True, unique=True
            ),
        ),
    ]
