# Generated by Django 6.0.5 on 2026-07-16 09:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_backfill_member_numbers"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRestriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("login", "Suspend login"),
                            ("payout", "Block money out (withdrawals / transfers)"),
                            ("payin", "Block money in (deposits)"),
                            ("freeze", "Freeze all money movement"),
                            ("community_create", "Restrict community creation"),
                            ("community_admin", "Restrict community administration"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("lifted", "Lifted"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "effective_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applied_by_label",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "approval_ref",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("lifted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lifted_by_label",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("lift_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restrictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="restriction_user_status_idx"
                    ),
                    models.Index(
                        fields=["kind", "status"], name="restriction_kind_status_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("user", "kind"),
                        name="uniq_active_restriction_per_kind",
                    )
                ],
            },
        ),
    ]
