# Generated by Django 6.0.5 on 2026-07-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerHeartbeat",
            fields=[
                (
                    "task_name",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("last_seen", models.DateTimeField()),
            ],
        ),
    ]
