# Generated by Django 6.0.5 on 2026-09-17 05:26
# Adds the ADR-0029 envelope (aggregate_key, dedup_key, occurred_at,
# schema_version) to OutboxEvent. Additive, backward-compatible: existing rows
# get blank keys and their occurred_at backfilled from created_at (the fact
# occurred when the row was written, not at migration time).

import django.utils.timezone
from django.db import migrations, models
from django.db.models import F


def backfill_occurred_at(apps, schema_editor):
    OutboxEvent = apps.get_model("core", "OutboxEvent")
    OutboxEvent.objects.update(occurred_at=F("created_at"))


def noop(apps, schema_editor):
    # Reverse is a no-op: occurred_at is dropped when the field is removed.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_workerheartbeat"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboxevent",
            name="aggregate_key",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=128
            ),
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="dedup_key",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=128
            ),
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="occurred_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="schema_version",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.RunPython(backfill_occurred_at, noop),
    ]
