# Generated by Django 6.0.5 on 2026-07-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mpesa", "0003_stk_advance_repayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="mpesac2btransaction",
            name="first_name",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="mpesac2btransaction",
            name="last_name",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="mpesac2btransaction",
            name="middle_name",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
