# Generated by Django 6.0.5 on 2026-07-05 17:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("backoffice", "0001_initial"),
        ("users", "0017_kycprofile_resubmission_requested"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "case_type",
                    models.CharField(default="kyc_individual", max_length=30),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted — awaiting review"),
                            (
                                "requires_info",
                                "Requires info — re-submission requested",
                            ),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("event_seq", models.PositiveIntegerField(default=0)),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "kyc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cases",
                        to="users.kycprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verification_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.PositiveIntegerField()),
                ("event_type", models.CharField(db_index=True, max_length=60)),
                (
                    "actor_kind",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("staff", "Staff"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=10,
                    ),
                ),
                (
                    "actor_label",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_case_events",
                        to="backoffice.staffaccount",
                    ),
                ),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_case_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="verification.verificationcase",
                    ),
                ),
            ],
            options={
                "ordering": ["case", "seq"],
            },
        ),
        migrations.CreateModel(
            name="CaseDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("id_front", "Front of ID"),
                            ("id_back", "Back of ID"),
                            ("selfie", "Selfie"),
                        ],
                        max_length=12,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "file",
                    models.FileField(
                        max_length=255, upload_to="verification/documents/"
                    ),
                ),
                ("sha256", models.CharField(blank=True, default="", max_length=64)),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("submission", "Initial submission"),
                            ("resubmission", "Re-submission"),
                            ("backfill", "Backfilled from legacy fields"),
                        ],
                        default="submission",
                        max_length=14,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="verification.verificationcase",
                    ),
                ),
            ],
            options={
                "ordering": ["case", "doc_type", "version"],
            },
        ),
        migrations.AddIndex(
            model_name="verificationcase",
            index=models.Index(
                fields=["state", "opened_at"], name="vcase_state_opened_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="caseevent",
            constraint=models.UniqueConstraint(
                fields=("case", "seq"), name="caseevent_case_seq_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="casedocument",
            constraint=models.UniqueConstraint(
                fields=("case", "doc_type", "version"),
                name="casedoc_case_type_version_uniq",
            ),
        ),
    ]
