# Generated by Django 6.0.5 on 2026-07-05 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0001_initial"),
        ("verification", "0002_backfill_cases"),
    ]

    operations = [
        migrations.CreateModel(
            name="RejectionReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                ("label", models.CharField(max_length=120)),
                ("customer_message", models.TextField()),
                ("active", models.BooleanField(default=True)),
                ("sort", models.PositiveIntegerField(default=100)),
            ],
            options={
                "ordering": ["sort", "code"],
            },
        ),
        migrations.AddField(
            model_name="verificationcase",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_verification_cases",
                to="backoffice.staffaccount",
            ),
        ),
        migrations.CreateModel(
            name="CaseNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_label",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "author_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_notes",
                        to="backoffice.staffaccount",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notes",
                        to="verification.verificationcase",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OcrResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engine", models.CharField(blank=True, default="", max_length=40)),
                ("detected", models.BooleanField(blank=True, null=True)),
                ("id_number_match", models.BooleanField(blank=True, null=True)),
                ("dob_match", models.BooleanField(blank=True, null=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ocr_results",
                        to="verification.verificationcase",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ocr_results",
                        to="verification.casedocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
