# Generated by Django 6.0.5 on 2026-07-06 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0001_initial"),
        ("users", "0017_kycprofile_resubmission_requested"),
        ("verification", "0004_seed_rejection_reasons"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationcase",
            name="subject_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="verificationcase",
            name="subject_type",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AlterField(
            model_name="casedocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("id_front", "Front of ID"),
                    ("id_back", "Back of ID"),
                    ("selfie", "Selfie"),
                    ("proof_of_funds", "Proof of funds"),
                    ("bank_statement", "Bank statement"),
                    ("invoice", "Invoice"),
                    ("receipt", "Receipt"),
                    ("supporting_doc", "Supporting document"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="verificationcase",
            name="case_type",
            field=models.CharField(
                choices=[
                    ("kyc_individual", "KYC — individual identity"),
                    ("edd_transaction", "EDD — large transaction"),
                    ("edd_drive", "EDD — large community drive"),
                ],
                db_index=True,
                default="kyc_individual",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="verificationcase",
            name="kyc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cases",
                to="users.kycprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationcase",
            index=models.Index(
                fields=["subject_type", "subject_id"], name="vcase_subject_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationcase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kyc__isnull", False),
                    models.Q(("subject_type", ""), _negated=True),
                    _connector="OR",
                ),
                name="vcase_has_kyc_or_subject",
            ),
        ),
    ]
