# Generated by Django 6.0.5 on 2026-09-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0007_verificationrequest_owned_by_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycprofile",
            name="evidence_retain_until",
            field=models.DateField(blank=True, null=True),
        ),
    ]
