# Generated by Django 5.2.14 on 2026-05-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0007_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationreadstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
