# Generated by Django 6.0.5 on 2026-06-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0008_alter_conversationreadstatus_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationreadstatus",
            name="last_read_message_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
