# Generated by Django 6.0.5 on 2026-06-19 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0005_seed_advance_accounts"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ledgerentry",
            name="ledger_le_contrib_dir_idx",
        ),
        migrations.RemoveIndex(
            model_name="ledgerentry",
            name="ledger_le_welfare_dir_idx",
        ),
        migrations.RemoveIndex(
            model_name="ledgerentry",
            name="ledger_le_shares_dir_idx",
        ),
        migrations.RemoveIndex(
            model_name="ledgerentry",
            name="ledger_le_user_idx",
        ),
        migrations.DeleteModel(
            name="LedgerEntry",
        ),
    ]
