# Generated by Django 6.0.5 on 2026-06-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0006_remove_ledgerentry_ledger_le_contrib_dir_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_currency", models.CharField(max_length=3)),
                ("quote_currency", models.CharField(max_length=3)),
                ("rate", models.DecimalField(decimal_places=10, max_digits=20)),
                ("effective_at", models.DateTimeField(db_index=True)),
                ("source", models.CharField(blank=True, max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-effective_at",),
                "indexes": [
                    models.Index(
                        fields=["base_currency", "quote_currency", "effective_at"],
                        name="ledger_fx_pair_eff_idx",
                    )
                ],
            },
        ),
    ]
