# Generated by Django 6.0.5 on 2026-06-22 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0007_exchangerate"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="financialtransaction",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="financial_transactions",
                to="tenants.tenant",
            ),
        ),
    ]
