# Generated by Django 6.0.5 on 2026-07-10 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0024_backfill_ct_financial_transaction"),
        ("ledger", "0008_account_tenant_financialtransaction_tenant"),
        ("tenants", "0004_crosstenantaccessattempt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="financialtransaction",
            index=models.Index(fields=["-created_at"], name="ledger_ft_created_idx"),
        ),
    ]
