# Generated by Django 6.0.5 on 2026-07-10 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0009_financialtransaction_ledger_ft_created_idx"),
        ("tenants", "0004_crosstenantaccessattempt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="account_uid",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="code",
            field=models.CharField(
                help_text="Human-facing Chart-of-Accounts code (mutable metadata, not identity).",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner__isnull", False)),
                fields=("owner", "fund_type", "fund_id"),
                name="ledger_acct_owner_fund_uniq",
            ),
        ),
    ]
