# Generated by Django 6.0.5 on 2026-07-10 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0012_restandardise_account_codes"),
        ("tenants", "0004_crosstenantaccessattempt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("owner__isnull", True), models.Q(("fund_type", ""), _negated=True)
                ),
                fields=("fund_type", "fund_id"),
                name="ledger_acct_pool_uniq",
            ),
        ),
    ]
