# Generated by Django 6.0.5 on 2026-07-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0014_create_pool_control_accounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialtransaction",
            name="counterparty_name",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
