# Generated by Django 6.0.5 on 2026-07-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0016_journal_immutable_triggers"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustodyArrangement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fund_type", models.CharField(max_length=30)),
                ("fund_id", models.PositiveIntegerField()),
                (
                    "trustee_label",
                    models.CharField(
                        default="Wepl (platform, in trust)", max_length=200
                    ),
                ),
                (
                    "legal_basis",
                    models.CharField(
                        choices=[
                            ("trust", "Held in trust for members"),
                            ("agency", "Held as agent for the group"),
                            ("own_funds", "Platform's own funds"),
                        ],
                        default="trust",
                        max_length=20,
                    ),
                ),
                ("governing_document", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fund_type", "fund_id"), name="uniq_custody_per_pool"
                    )
                ],
            },
        ),
    ]
