# Generated by Django 6.0.5 on 2026-07-18 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0019_seed_retained_surplus_gl"),
        ("organizations", "0002_program"),
        ("tenants", "0008_rls_program"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="account",
            name="ledger_acct_pool_uniq",
        ),
        migrations.AddField(
            model_name="account",
            name="owner_org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_accounts",
                to="organizations.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["owner_org", "fund_type", "fund_id"],
                name="ledger_acct_ownerorg_fund_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner_org__isnull", False)),
                fields=("owner_org", "fund_type", "fund_id"),
                name="ledger_acct_ownerorg_fund_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("owner__isnull", True),
                    ("owner_org__isnull", True),
                    models.Q(("fund_type", ""), _negated=True),
                ),
                fields=("fund_type", "fund_id"),
                name="ledger_acct_pool_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("owner__isnull", False),
                    ("owner_org__isnull", False),
                    _negated=True,
                ),
                name="ledger_acct_single_owner",
            ),
        ),
    ]
