"""Drop FinancialTransaction's Daraja columns (ADR-0030, closes #159).

The ledger is the book of record and holds no rail vocabulary. PaymentIntent is
authoritative for the rail dimension as of the previous release, and
``payments.0008`` carried every value in these columns into an intent — so this
removes duplicated data, not the only copy.

Split from that release on purpose: Render serves the previous instance until
the new one is healthy, and migrations run at deploy, so dropping a column in
the same deploy that stops reading it would leave the old code querying a column
that is gone. That release stopped reading; this one drops (additive-first,
P-7/E-2).

``mpesa_checkout_id`` was never written by any code path.
"""
# Generated by Django 6.0.5 on 2026-09-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0020_remove_account_ledger_acct_pool_uniq_and_more"),
        # The backfill reads these columns through the historical model, so on a
        # database that has never seen them (a fresh install, the test DB) it has
        # to run while they still exist. Django will not infer that ordering.
        ("payments", "0008_backfill_payout_intents"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financialtransaction",
            name="mpesa_checkout_id",
        ),
        migrations.RemoveField(
            model_name="financialtransaction",
            name="mpesa_conversation_id",
        ),
        migrations.RemoveField(
            model_name="financialtransaction",
            name="mpesa_receipt",
        ),
    ]
