# Generated by Django 6.0.5 on 2026-06-21 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ledger", "0006_remove_ledgerentry_ledger_le_contrib_dir_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LimitRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("GLOBAL", "Global (platform-wide)"),
                            ("PER_USER", "Per user"),
                        ],
                        default="PER_USER",
                        max_length=10,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("ANY", "Any"),
                            ("PAYIN", "Pay-in"),
                            ("PAYOUT", "Pay-out"),
                        ],
                        default="PAYOUT",
                        max_length=6,
                    ),
                ),
                (
                    "op_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CONTRIBUTION", "Member Contribution"),
                            ("DISBURSEMENT", "Disbursement"),
                            ("STANDING_ORDER", "Standing Order Payout"),
                            ("ROSCA_PAYOUT", "ROSCA Payout"),
                            ("ADVANCE_DISBURSEMENT", "Emergency Advance Disbursement"),
                            ("ADVANCE_REPAYMENT", "Emergency Advance Repayment"),
                            ("WELFARE_CONTRIBUTION", "Welfare Contribution"),
                            ("WELFARE_CLAIM", "Welfare Claim Disbursement"),
                            ("SHARES_PURCHASE", "Shares Purchase"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("TXN", "Per transaction"),
                            ("HOUR", "Rolling hour"),
                            ("DAY", "Calendar day"),
                            ("WEEK", "Calendar week"),
                            ("MONTH", "Calendar month"),
                        ],
                        default="DAY",
                        max_length=5,
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("max_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[("DENY", "Deny"), ("HOLD", "Hold for review")],
                        default="DENY",
                        max_length=4,
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100, help_text="Lower runs first; DENY short-circuits."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("priority", "id"),
            },
        ),
        migrations.CreateModel(
            name="ControlDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("ALLOW", "Allow"),
                            ("DENY", "Deny"),
                            ("HOLD", "Hold"),
                        ],
                        max_length=5,
                    ),
                ),
                ("op_type", models.CharField(max_length=30)),
                ("direction", models.CharField(max_length=6)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("reason", models.TextField(blank=True)),
                (
                    "window_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("window_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "financial_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="control_decisions",
                        to="ledger.financialtransaction",
                    ),
                ),
                (
                    "subject_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="control_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decisions",
                        to="controls.limitrule",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["decision", "created_at"], name="ctrl_decision_idx"
                    ),
                    models.Index(
                        fields=["subject_user", "created_at"], name="ctrl_subject_idx"
                    ),
                ],
            },
        ),
    ]
