# Generated by Django 6.0.5 on 2026-06-22 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controls", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HeldMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[("DENY", "Denied"), ("HOLD", "Held")], max_length=5
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("RELEASED", "Released"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("op_type", models.CharField(max_length=30)),
                ("direction", models.CharField(max_length=6)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("recipient_phone", models.CharField(blank=True, max_length=20)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("context_type", models.CharField(blank=True, max_length=30)),
                ("context_id", models.PositiveIntegerField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_held_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="held_movements",
                        to="controls.limitrule",
                    ),
                ),
                (
                    "subject_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="held_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="held_status_idx"
                    )
                ],
            },
        ),
    ]
