# Generated by Django 6.0.5 on 2026-06-22 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controls", "0002_heldmovement"),
        ("tenants", "0003_rls_policies"),
    ]

    operations = [
        migrations.AddField(
            model_name="limitrule",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="limit_rules",
                to="tenants.tenant",
            ),
        ),
    ]
