# Generated by Django 6.0.5 on 2026-07-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controls", "0004_controloverride"),
    ]

    operations = [
        migrations.AlterField(
            model_name="limitrule",
            name="op_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CONTRIBUTION", "Member Contribution"),
                    ("DISBURSEMENT", "Disbursement"),
                    ("STANDING_ORDER", "Standing Order Payout"),
                    ("ROSCA_PAYOUT", "ROSCA Payout"),
                    ("ADVANCE_DISBURSEMENT", "Emergency Advance Disbursement"),
                    ("ADVANCE_REPAYMENT", "Emergency Advance Repayment"),
                    ("WELFARE_CONTRIBUTION", "Welfare Contribution"),
                    ("WELFARE_CLAIM", "Welfare Claim Disbursement"),
                    ("SHARES_PURCHASE", "Shares Purchase"),
                    ("EXTERNAL_INCOME", "External Income into Pool"),
                    ("SURPLUS_DISTRIBUTION", "Retained Surplus Distribution"),
                ],
                max_length=30,
            ),
        ),
    ]
