# Generated by Django 6.0.5 on 2026-05-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('community_created', 'Community Created'), ('community_joined', 'Community Joined'), ('community_left', 'Community Left'), ('conversation_created', 'Conversation Created'), ('message_sent', 'Message Sent'), ('contribution_created', 'Contribution Created'), ('contribution_payment', 'Contribution Payment'), ('payment_made', 'Payment Made')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
