# Generated by Django 5.2.14 on 2026-05-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('community_created', 'Community Created'), ('community_joined', 'Community Joined'), ('community_left', 'Community Left'), ('conversation_created', 'Conversation Created'), ('message_sent', 'Message Sent'), ('contribution_created', 'Contribution Created'), ('contribution_payment', 'Contribution Payment'), ('standing_order_executed', 'Standing Order Executed'), ('welfare_contribution', 'Welfare Contribution'), ('payment_made', 'Payment Made')], max_length=50),
        ),
    ]
