# Generated by Django 6.0.5 on 2026-06-25 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0004_alter_activity_activity_type"),
        ("communities", "0014_alter_community_tenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="community",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="communities.community",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="params",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="activity",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "Private (actor only)"),
                    ("community", "Community members"),
                    ("public", "Public"),
                ],
                default="private",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("community_created", "Community Created"),
                    ("community_joined", "Community Joined"),
                    ("community_left", "Community Left"),
                    (
                        "community_ownership_transferred",
                        "Community Ownership Transferred",
                    ),
                    ("conversation_created", "Conversation Created"),
                    ("message_sent", "Message Sent"),
                    ("contribution_created", "Contribution Created"),
                    ("contribution_payment", "Contribution Payment"),
                    ("standing_order_executed", "Standing Order Executed"),
                    ("welfare_contribution", "Welfare Contribution"),
                    ("payment_made", "Payment Made"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["community", "-created_at"], name="activity_comm_date_idx"
            ),
        ),
    ]
