# Generated by Django 6.0.5 on 2026-07-12 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0005_activity_community_activity_params_and_more"),
        ("tenants", "0005_extend_rls_policies"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="tenants.tenant",
            ),
        ),
    ]
