# Generated by Django 6.0.5 on 2026-09-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0006_activity_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="source_event_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
