# Generated by Django 6.0.5 on 2026-05-11 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contributionaccount',
            name='contribution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='contributions.contribution'),
        ),
        migrations.AddField(
            model_name='contributionbalance',
            name='contribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='contributions.contribution'),
        ),
        migrations.AddField(
            model_name='contributionbalance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contributionparticipant',
            name='contribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='contributions.contribution'),
        ),
        migrations.AddField(
            model_name='contributionparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contributiontransaction',
            name='contribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='contributions.contribution'),
        ),
        migrations.AddField(
            model_name='contributiontransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='contributionbalance',
            unique_together={('contribution', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='contributionparticipant',
            unique_together={('contribution', 'user')},
        ),
    ]
