# Generated by Django 6.0.5 on 2026-05-16 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_add_contribution_status'),
        ('contributions', '0005_restructure_funds'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contribution_type',
            field=models.CharField(blank=True, default='POOL', max_length=20),
        ),
        migrations.AlterField(
            model_name='welfarefund',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='welfare_funds', to='communities.community'),
        ),
    ]
