# Generated by Django 6.0.5 on 2026-05-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0007_add_standing_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='welfareclaim',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='welfareclaim',
            name='b2c_conversation_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='welfareclaim',
            name='mpesa_receipt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
