# Generated by Django 5.2.14 on 2026-05-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0013_standingorder_schedule'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contribution',
            new_name='contrib_comm_active_idx',
            old_name='contribution_community_active_idx',
        ),
        migrations.RenameIndex(
            model_name='contribution',
            new_name='contrib_vis_active_idx',
            old_name='contribution_visibility_active_idx',
        ),
        migrations.RenameIndex(
            model_name='contributionbalance',
            new_name='contrib_bal_user_idx',
            old_name='contrib_balance_contrib_user_idx',
        ),
        migrations.RenameIndex(
            model_name='contributionparticipant',
            new_name='contrib_part_user_act_idx',
            old_name='contrib_participant_user_active_idx',
        ),
        migrations.AlterField(
            model_name='disbursementrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXECUTED', 'Executed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
