# Generated by Django 5.2.14 on 2026-06-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0017_contribution_governance_locked_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='member_target_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
