# Generated by Django 5.2.14 on 2026-06-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0018_contribution_member_target_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='amendment_proposer',
            field=models.CharField(choices=[('creator', 'Creator only'), ('admins', 'Admins and treasurers'), ('members', 'Any active participant')], default='creator', max_length=10),
        ),
        migrations.AddField(
            model_name='contribution',
            name='amendment_voting_threshold',
            field=models.CharField(choices=[('admins', 'Admins only'), ('25', '25% of members'), ('50', '50% of members'), ('100', '100% of members')], default='admins', help_text='Threshold to approve a contribution amendment proposal.', max_length=10),
        ),
        migrations.AddField(
            model_name='contribution',
            name='late_contribution_grace_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Days after end_date that contributions are still accepted (grace policy only).'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='late_contribution_policy',
            field=models.CharField(choices=[('open', 'Allow contributions anytime'), ('strict', 'Block contributions after end date'), ('grace', 'Allow during a grace period after end date')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='contribution',
            name='transaction_visibility',
            field=models.CharField(choices=[('all', 'All participants see all transactions'), ('own', 'Each member sees only their own transactions'), ('admins_all', 'Admins see all; members see their own only')], default='all', max_length=15),
        ),
    ]
