# Generated by Django 6.0.5 on 2026-06-20 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0019_contribution_amendment_proposer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contributionaccount",
            name="contribution",
        ),
        migrations.AlterUniqueTogether(
            name="contributionbalance",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="contributionbalance",
            name="contrib_bal_user_idx",
        ),
        migrations.RemoveField(
            model_name="contribution",
            name="current_amount",
        ),
        migrations.RemoveField(
            model_name="sharesfund",
            name="total_pool",
        ),
        migrations.RemoveField(
            model_name="welfarefund",
            name="balance",
        ),
        migrations.DeleteModel(
            name="ContributionAccount",
        ),
        migrations.DeleteModel(
            name="ContributionBalance",
        ),
    ]
