# Generated by Django 6.0.5 on 2026-06-20 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0020_remove_contributionaccount_contribution_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="welfareclaim",
            name="b2c_conversation_id",
        ),
    ]
