# Generated by Django 6.0.5 on 2026-07-06 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0016_community_status_communitymembership_rejoined_at"),
        ("contributions", "0021_remove_welfareclaim_b2c_conversation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="community",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contributions",
                to="communities.community",
            ),
        ),
        migrations.AlterField(
            model_name="sharesfund",
            name="community",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shares_fund",
                to="communities.community",
            ),
        ),
        migrations.AlterField(
            model_name="welfarefund",
            name="community",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="welfare_funds",
                to="communities.community",
            ),
        ),
    ]
