# Generated by Django 6.0.5 on 2026-07-09 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0022_alter_contribution_community_and_more"),
        ("ledger", "0008_account_tenant_financialtransaction_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributiontransaction",
            name="financial_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contribution_transactions",
                to="ledger.financialtransaction",
            ),
        ),
    ]
