# Generated by Django 6.0.5 on 2026-07-13 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0024_backfill_ct_financial_transaction"),
        ("organizations", "0002_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="program",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contribution_profile",
                to="organizations.program",
            ),
        ),
        migrations.AddField(
            model_name="sharesfund",
            name="program",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shares_profile",
                to="organizations.program",
            ),
        ),
        migrations.AddField(
            model_name="welfarefund",
            name="program",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="welfare_profile",
                to="organizations.program",
            ),
        ),
    ]
