# Generated by Django 6.0.5 on 2026-07-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0026_backfill_programs"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="contributiontransaction",
            name="contrib_tx_contrib_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="contributiontransaction",
            name="contrib_tx_user_date_idx",
        ),
        migrations.DeleteModel(
            name="ContributionTransaction",
        ),
    ]
