# Generated by Django 6.0.5 on 2026-09-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0030_drop_advance_amount_repaid"),
    ]

    operations = [
        migrations.AddField(
            model_name="disbursementrequest",
            name="decide_by",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disbursementrequest",
            name="kind",
            field=models.CharField(
                choices=[("payout", "Payout"), ("exit", "Exit settlement")],
                db_default="payout",
                default="payout",
                max_length=10,
            ),
        ),
    ]
