# Generated by Django 6.0.5 on 2026-09-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0031_disbursement_exit_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disbursementrequest",
            name="kind",
            field=models.CharField(
                choices=[
                    ("payout", "Payout"),
                    ("exit", "Exit settlement"),
                    ("windup", "Wind-up payout"),
                ],
                db_default="payout",
                default="payout",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="poolactionrequest",
            name="action",
            field=models.CharField(
                choices=[
                    ("EXPENSE", "Pool expense"),
                    ("DISTRIBUTION", "Surplus distribution"),
                    ("WIND_UP", "Wind-up"),
                ],
                max_length=20,
            ),
        ),
    ]
