# Generated by Django 6.0.5 on 2026-09-27 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0033_welfare_wind_up"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="beneficiary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="collections_for",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="disbursementrequest",
            name="kind",
            field=models.CharField(
                choices=[
                    ("payout", "Payout"),
                    ("exit", "Exit settlement"),
                    ("windup", "Wind-up payout"),
                    ("handover", "Collection hand-over"),
                ],
                db_default="payout",
                default="payout",
                max_length=10,
            ),
        ),
    ]
