# Generated by Django 6.0.5 on 2026-07-05 12:41

import apps.backoffice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(blank=True, default="", max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "must_change_password",
                    models.BooleanField(
                        default=True,
                        help_text="Forces the operator to set their own password before using the console.",
                    ),
                ),
                ("password_changed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="staff_accounts", to="auth.group"
                    ),
                ),
            ],
            options={
                "verbose_name": "staff account",
                "ordering": ["email"],
            },
            managers=[
                ("objects", apps.backoffice.models.StaffAccountManager()),
            ],
        ),
    ]
