# Generated by Django 6.0.5 on 2026-07-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffaccount",
            name="totp_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staffaccount",
            name="totp_recovery_codes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="staffaccount",
            name="totp_secret",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
