# Generated by Django 6.0.5 on 2026-07-09 07:06

import apps.core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0002_staffaccount_totp_confirmed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffaccount",
            name="totp_secret",
            field=apps.core.encryption.EncryptedTextField(blank=True, default=""),
        ),
    ]
