# Generated by Django 6.0.5 on 2026-07-09 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0003_alter_staffaccount_totp_secret"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpsApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=64)),
                ("params", models.JSONField(default=dict)),
                ("reason", models.TextField()),
                ("summary", models.CharField(blank=True, default="", max_length=255)),
                (
                    "target_type",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("target_id", models.CharField(blank=True, default="", max_length=64)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                            ("FAILED", "Execution failed"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True, default="")),
                ("result", models.JSONField(blank=True, default=dict)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_requests_decided",
                        to="backoffice.staffaccount",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_requests_made",
                        to="backoffice.staffaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "requested_at"], name="ops_appr_status_idx"
                    )
                ],
            },
        ),
    ]
