# Generated by Django 6.0.5 on 2026-06-24 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0008_account_tenant_financialtransaction_tenant"),
        ("payments", "0003_performance_indexes"),
        ("tenants", "0004_crosstenantaccessattempt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReconciliationDrift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("stuck_pending_intent", "Stuck pending intent"),
                            (
                                "intent_ft_mismatch",
                                "Intent/FinancialTransaction state mismatch",
                            ),
                            (
                                "ft_without_journal",
                                "Successful FT without a posted journal",
                            ),
                            (
                                "ft_stuck_processing",
                                "FinancialTransaction stuck in processing",
                            ),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("subject_type", models.CharField(max_length=30)),
                ("subject_id", models.CharField(max_length=64)),
                ("detail", models.TextField(blank=True, default="")),
                ("detected_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["kind", "resolved_at"], name="drift_kind_resolved_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("resolved_at__isnull", True)),
                        fields=("kind", "subject_type", "subject_id"),
                        name="uniq_open_drift_per_subject",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(db_index=True, max_length=30)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("collection", "Collection (pay-in)"),
                            ("payout", "Payout (pay-out)"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("reversed", "Reversed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="KES", max_length=3)),
                (
                    "provider_ref",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("receipt", models.CharField(blank=True, default="", max_length=64)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("op_type", models.CharField(blank=True, default="", max_length=30)),
                ("failure_reason", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "financial_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_intents",
                        to="ledger.financialtransaction",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_intents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_intents",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "provider_ref"], name="pi_provider_ref_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"], name="pi_status_created_idx"
                    ),
                ],
            },
        ),
    ]
