# Generated by Django 6.0.5 on 2026-07-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_reconciliationdrift_paymentintent"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="payment",
            name="payment_contrib_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payment_user_date_idx",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
