# Generated by Django 6.0.5 on 2026-07-12 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_providerevent_remove_paymentintent_failure_reason_and_more"),
        ("tenants", "0005_extend_rls_policies"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerevent",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="provider_events",
                to="tenants.tenant",
            ),
        ),
    ]
