# Generated by Django 6.0.5 on 2026-09-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_backfill_payout_intents"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentintent",
            name="purpose",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Collections: what the pay-in is for (e.g. contribution, welfare).",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="subject_ref",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Collections: the id of the thing the pay-in is for.",
                max_length=64,
            ),
        ),
    ]
