# Generated by Django 6.0.5 on 2026-07-13 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0006_rls_provider_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.UUIDField(editable=False, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "archetype",
                    models.CharField(
                        choices=[("community", "Community")], max_length=30
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organizations",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "indexes": [
                    models.Index(fields=["archetype"], name="org_archetype_idx")
                ],
            },
        ),
    ]
