# Generated by Django 6.0.5 on 2026-07-13 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("tenants", "0007_rls_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.UUIDField(editable=False, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("contribution", "Contribution / Pool"),
                            ("welfare", "Welfare Fund"),
                            ("shares", "Shares Fund"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programs",
                        to="organizations.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programs",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "indexes": [
                    models.Index(fields=["program_type"], name="program_type_idx"),
                    models.Index(fields=["organization"], name="program_org_idx"),
                ],
            },
        ),
    ]
